### ISSUE TITLE
Problem with Saiku Reporting

### ISSUE THREAD

**Issue by jagnaldo** [Mgiepz/saiku-adhoc#126]
Hi,

i installed saiku-adhoc-plugin-1.0-RC1 from 'http://ci.analytical-labs.com/job/saiku-adhoc-plugin/lastSuccessfulBuild/artifact/saiku-adhoc-plugin/target/' and when i run on bi-server 3.10 i receive the message: 'ReportGenerator.ERROR_0001 - The CDA Datafactory could not process the query'.

Looking at the catalina log show me the errors: 07:21:13,216 ERROR [SolutionRepositoryBase] SolutionRepository.ERROR_0023 - Invalid publish location: Root Folder 07:21:13,226 ERROR [ReportGeneratorService] org.pentaho.reporting.engine.classic.core.ReportDataFactoryException: Failed to send request 07:21:13,226 ERROR [QueryResource] Cannot generate report (67D1E0AA-545C-F797-B3B6-51C0D118E00B) org.saiku.adhoc.exceptions.SaikuAdhocException: ReportGenerator.ERROR_0001 - The CDA Datafactory could not process the query

any help ?

Thanks.

**Comment by Mgiepz** [comment]
Please do the following:
create a solution and a folder like pentaho-solutions/temp/cda, that every user can access. 
Then go to saiku-adhoc-properties and set these two properties like:
saiku-adhoc.temp.solution=temp
saiku-adhoc.temp.path=cda

Refresh your repository and reboot your server. 

p.s.: we're working on a better solution

**Comment by jagnaldo** [comment]
Thank you for the answer..

I did everything but i still have the same problem.

Below is my saiku-adhoc-properties:

saiku-adhoc.default.template=saiku_small
saiku-adhoc.cda.user=joe
saiku-adhoc.cda.password=password
saiku-adhoc.metadata.file=c:/TargetPlatforms/saiku-server/tomcat/webapps/metadata.xmi
saiku-adhoc.temp.solution=temp
saiku-adhoc.temp.path=cda

P.S. I´v to change the saiku-adhoc.metadata.file ?

Thanks

**Comment by jbeleni** [comment]
I did Mgiepz solution and WORK´S!

Thank´s

**Comment by Mgiepz** [comment]
@jagnaldo: the metadata file is only for the standalone version. not the pentaho plugin. Did you also CREATE the solution and the path in your repository?

**Comment by jagnaldo** [comment]
Hi  Mgiepz , yes i created... see the screen above;;;

thanks

[image: Imagem inline 1]

2012/3/15 Mgiepz <
reply@reply.github.com

**Comment by Mgiepz** [comment]
sorry, i cant see your image. post it to imagebin for example

**Comment by jagnaldo** [comment]
Posted in  http://derp.co.uk/c0851

Thank you !

2012/3/15 Mgiepz <
reply@reply.github.com

**Comment by Mgiepz** [comment]
hm, i am not really sure what is happening then. but i have just refactored something so that we wont need a special directory and a named user in the saiku-adhoc.properties. i will test that and check it in soon.

**Comment by jagnaldo** [comment]
Ok, thank you !

**Comment by Mgiepz** [comment]
@jagnaldo: If youre still having problem, try to update your installation using the ctools-installer with the -b dev option. It should get you the latest version of saiku reporting which doesnt need any paths and users to be configured in saiku-adhoc.properties. Maybe you should even try it with a clean biserver 3.10-stable first.

**Comment by jagnaldo** [comment]
Hi  Mgiepz, i updated my installation using ctools-installer with the -b dev option but i still have the same problem. My environment is Pentaho deployed in Liferay and CAS, dou you think that the problem is because i´m using Pentaho with SSL ? Here is the image with my environment. http://derp.co.uk/2c489
Thank you.

**Comment by jagnaldo** [comment]
Hi Mgiepz, sorry ... it works fine, the error was on my metada model, the query was wrong. My conclusion is that we have to work with the dev branch isn´t it ?
thank you

**Comment by fbr01** [comment]
I have the problem if I have a space or an accent in category name.
Basic Ctools installation on Pentaho 3.9CE (Linux platform)

**Comment by Sigehere** [comment]
Hello Friends,
I got same error as follow:
ReportGenerator.ERROR_0001 - The CDA Datafactory could not process the query

and in pentaho.log file i got following error
2013-02-11 14:55:07,297 ERROR [org.saiku.adhoc.service.cda.PluginUtils] Failed to execute call to plugin: java.lang.NullPointerException
2013-02-11 14:55:07,297 ERROR [org.saiku.adhoc.service.report.ReportGeneratorService] org.pentaho.reporting.engine.classic.core.ReportDataFactoryException: Failed to send request
2013-02-11 14:55:07,297 ERROR [org.saiku.adhoc.rest.QueryResource] Cannot generate report (A10F0DB7-E9A6-2B22-89A9-665BDA3055DD)
org.saiku.adhoc.exceptions.SaikuAdhocException: ReportGenerator.ERROR_0001 - The CDA Datafactory could not process the query 
        at org.saiku.adhoc.service.report.ReportGeneratorService.processReport(ReportGeneratorService.java:293)
        at org.saiku.adhoc.service.report.ReportGeneratorService.renderReportHtml(ReportGeneratorService.java:153)
        at org.saiku.adhoc.rest.QueryResource.generateReport(QueryResource.java:271)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:168)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:71)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:280)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1341)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1273)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1223)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1213)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:414)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
        at org.codehaus.enunciate.modules.jersey.EnunciateJerseyServletContainer.service(EnunciateJerseyServletContainer.java:239)
        at org.saiku.adhoc.service.EnunciateJerseyPluginServlet.service(EnunciateJerseyPluginServlet.java:76)
        at org.saiku.adhoc.service.ServletAdapterContentGenerator.createContent(ServletAdapterContentGenerator.java:80)
        at org.pentaho.platform.web.servlet.GenericServlet.doGet(GenericServlet.java:261)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.pentaho.platform.web.http.filters.PentahoWebContextFilter.doFilter(PentahoWebContextFilter.java:142)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.pentaho.platform.web.http.filters.PentahoRequestContextFilter.doFilter(PentahoRequestContextFilter.java:84)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:378)
        at org.springframework.security.intercept.web.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:109)
        at org.springframework.security.intercept.web.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:390)
        at org.springframework.security.ui.ExceptionTranslationFilter.doFilterHttp(ExceptionTranslationFilter.java:101)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:390)
        at org.pentaho.platform.web.http.security.SecurityStartupFilter.doFilter(SecurityStartupFilter.java:103)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:390)
        at org.springframework.security.providers.anonymous.AnonymousProcessingFilter.doFilterHttp(AnonymousProcessingFilter.java:105)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:390)
        at org.pentaho.platform.web.http.security.RequestParameterAuthenticationFilter.doFilter(RequestParameterAuthenticationFilter.java:169)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:390)
        at org.springframework.security.ui.basicauth.BasicProcessingFilter.doFilterHttp(BasicProcessingFilter.java:174)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:390)
        at org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractProcessingFilter.java:278)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:390)
        at org.springframework.security.ui.logout.LogoutFilter.doFilterHttp(LogoutFilter.java:89)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:390)
        at org.pentaho.platform.web.http.security.HttpSessionReuseDetectionFilter.doFilter(HttpSessionReuseDetectionFilter.java:134)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:390)
        at org.springframework.security.context.HttpSessionContextIntegrationFilter.doFilterHttp(HttpSessionContextIntegrationFilter.java:235)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:390)
        at org.springframework.security.wrapper.SecurityContextHolderAwareRequestFilter.doFilterHttp(SecurityContextHolderAwareRequestFilter.java:91)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:390)
        at org.springframework.security.util.FilterChainProxy.doFilter(FilterChainProxy.java:175)
        at org.springframework.security.util.FilterToBeanProxy.doFilter(FilterToBeanProxy.java:99)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.pentaho.platform.web.http.filters.SystemStatusFilter.doFilter(SystemStatusFilter.java:60)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.pentaho.platform.web.http.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:113)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:662)

Please help me .
I am in big troubled.

**Comment by Pierre-Antoine** [comment]
I have the same problem... Did you find a solution?

Edit: CDA was not installed actually... It works fine now.

**Comment by kbir** [comment]
hi, am installed saiku-adhoc rporting tool. but i con't access published cube to create report.
but can access in saiku analytics plugin..
plrase help me..
thanks

**Comment by eduardoarantes** [comment]
I'm new to Pentaho and I couldn't figure out what a solution is and how to create it.

Could you point me to the right direction?
Eduardo
