### ISSUE TITLE
error on prpt export

### ISSUE THREAD

**Issue by Mgiepz** [Mgiepz/saiku-adhoc#27]
when exporting prpts there is the error

Caused by: java.lang.ClassNotFoundException: org.pentaho.reporting.engine.classi
c.core.modules.parser.base.PasswordEncryptionService
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at org.pentaho.platform.plugin.services.pluginmgr.PluginClassLoader.load
Class(PluginClassLoader.java:214)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
        ... 93 more

which depends on the reporting version.

**Comment by Mgiepz** [comment]
seems like pentaho-reporting-engine-classic-extensions-cda-TRUNK-SNAPSHOT.jar does not work with biserver that has 3.8.3 reporting. we need pentaho-reporting-engine-classic-extensions-cda-3.8-SNAPSHOT.jar instead.

**Comment by Mgiepz** [comment]
this has been described on the forum and can be read in the README
